### ISSUE TITLE
大佬啥时候能出个部署教程

### ISSUE THREAD

**Issue by otakurisu** [ronething/music-interface#2]
提供的那个有点看不懂呀OTZ

**Comment by ronething** [comment]
> 提供的那个有点看不懂呀OTZ

不如说一下哪里看不懂？

**Comment by otakurisu** [comment]
![9SG3B})EXP9~))IB7$SPKLC](https://user-images.githubusercontent.com/32485369/57054196-983cf680-6cc5-11e9-8d36-6e0633c23424.png)
这个一定要py3.6的版本吗，我用的最新版本

**Comment by otakurisu** [comment]
![094IOR(DF52VOWNP9@14EYN](https://user-images.githubusercontent.com/32485369/57055140-d89f7300-6ccb-11e9-8d9e-d0b9ffdc6abf.png)

**Comment by ronething** [comment]
- 关于版本问题可以通过 --python 参数指定 如 `pipenv install --python /Users/ronething/anaconda3/bin/python`

- 第二个问题则是要在 `app/config` 目录下面建立 `secure.py` 文件 README.md 中有提到。

**Comment by otakurisu** [comment]
多谢大佬，能运行了。
现在有个问题，这个只能在服务器本地访问，但是外网无法访问，端口也打开了6379和7000，redia用的是这个https://github.com/MicrosoftArchive/redis/releases

**Comment by ronething** [comment]
`pipenv run python manage.py` 这个只是本地开发使用。如果要部署上服务器建议使用 gunicorn+nginx+supervisor 具体可以参考 mp-music 里面或者直接百度谷歌应该更详细。

**Comment by Nekoer** [comment]
你这个端口能改吗，我改成其他的运行不了

**Comment by ronething** [comment]
close 需要再开issue
